apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-admin-deployment
  namespace: develop
  labels:
    app: dd-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-admin
  template:
    metadata:
       name: dd-admin
       namespace: develop
       labels:
        app: dd-admin
    spec:
      containers:
        - name: dd-admin
          image: ghcr.io/arctica-th/destinydraw-admin-develop:v0.0.${APP_VERSION}
          resources:
          ports:
            - containerPort: 80
      
---

apiVersion: v1
kind: Service
metadata:
  name: dd-admin-service
  namespace: develop
spec:
  type: NodePort
  selector:
    app: dd-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30031
      
---