apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-admin-deployment
  namespace: destinydraw
  labels:
    app: dd-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-admin
  template:
    metadata:
       name: dd-admin
       namespace: destinydraw
       labels:
        app: dd-admin
    spec:
      containers:
        - name: dd-admin
          image: ghcr.io/arctica-th/destinydraw-admin:v0.0.${APP_VERSION}
          resources:
          ports:
            - containerPort: 80
      
---

apiVersion: v1
kind: Service
metadata:
  name: dd-admin-service
  namespace: destinydraw
spec:
  type: NodePort
  selector:
    app: dd-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dd-admin-ing
  namespace: uat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "destinydraw.com"
      http:
        paths:
          - path: /dd-admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dd-admin-service
                port:
                  number: 80