apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-admin-deployment
  labels:
    app: dd-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-admin
  template:
    metadata:
      labels:
        app: dd-admin
    spec:
      containers:
      - name: dd-admin
        image: deadmandrive/destinydraw-admin:v0.0.32
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dd-admin-service
spec:
  type: NodePort
  selector:
    app: dd-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021