name: MTG_Admin

on:
  workflow_dispatch:
    inputs:
      version_Image:
        description: "input version image"
        default: ""
        type: "string"
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: destinydraw-admin

jobs:
  Deploy_to_Kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: remote to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
           cd app
           rm -rf MTG-Admin
           git clone https://${{ secrets.USERNAME }}:${{ secrets.PASS_TOKEN }}@github.com/Arctica-th/MTG-Admin.git
           ls -lrt
           cd MTG-Admin
           ls -lrt
           sudo crictl pull --creds ${{ secrets.USERNAME }}:${{ secrets.PASS_TOKEN }} ${{ env.REGISTRY }}/arctica-th/${{ env.IMAGE_NAME }}-uat:${{ inputs.version_Image }}
           export IMAGE="${{ env.REGISTRY }}/arctica-th/${{ env.IMAGE_NAME }}-uat:${{ inputs.version_Image }}"
           echo "IMAGE : ${IMAGE}"
           cat k8s/dd-admin.yaml | envsubst | sudo kubectl apply -f -