name: MTG_Admin

on:
  workflow_dispatch:
  pull_request:
    branches: [ uat ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: destinydraw-admin
  ENVIRONMENT: uat

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: check repository
        uses: actions/checkout@v3

      - name: Login to Registry github
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS_TOKEN }}

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME }}-${{ env.ENVIRONMENT }}
          tags: v0.0.${{github.run_number}}
          dockerfile : Dockerfile.ci
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS_TOKEN }}

      # - name: test manual Build the Docker image
      #   run: |
      #     sudo docker build . -t deadmandrive/destinydraw-web:v0.0.${{github.run_number}}

      # # test image can run successful
      # # sudo docker run --name MTG-admin -p 3000:80 -d deadmandrive/destinydraw-web
  Remote:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: remote to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
           cd app
           rm -rf MTG-Admin
           git clone https://${{ secrets.USERNAME }}:${{ secrets.PASS_TOKEN }}@github.com/Arctica-th/MTG-Admin.git
           ls -lrt
           cd MTG-Admin && git checkout ${{ env.ENVIRONMENT }}
           ls -lrt
           sudo crictl pull --creds ${{ secrets.USERNAME }}:${{ secrets.PASS_TOKEN }} ${{ env.REGISTRY }}/arctica-th/${{ env.IMAGE_NAME }}-${{ env.ENVIRONMENT }}:v0.0.${{github.run_number}}
           export APP_VERSION="${{github.run_number}}"
           echo "APP_VERSION : ${APP_VERSION}"
           cat k8s/dd-admin-uat.yaml | envsubst | sudo kubectl apply -f -